plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace = "in.kvapps.wirelessstart.wear"
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    defaultConfig {
        applicationId = "in.kvapps.wirelessstart"
        minSdk = 30
        targetSdk = 36
        versionCode = 1
        versionName = "1.0"

    }

    buildTypes {
        release {
            optimization {
                enable = false
            }
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

dependencies {
    implementation(libs.play.services.wearable)

    // Custom Shared Module to hold common code between PhoneApp and WearApp
    implementation project(':shared')
}